FROM node:20.19

WORKDIR /usr/src/frontend

# Skip Cypress Install
ENV CYPRESS_INSTALL_BINARY 0

# Install dependencies first
COPY package*.json ./
RUN npm install --unsafe-perm

COPY . .

ARG PORT=3000
ENV PORT $PORT

ARG NODE_ENV=production
ENV NODE_ENV $NODE_ENV

# Build the application for staging
RUN npm run build

# Remove dev dependencies for smaller image
RUN npm prune --production

EXPOSE $PORT

# Start the production server
CMD ["npm", "run", "start"]